# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "01c0c9f19c37d9693c772c9246c6a9a1"
application_url = "https://c752-60-176-176-114.ngrok-free.app"
embedded = true
name = "comment-app"
handle = "comment-app-10"

[build]
include_config_on_deploy = true
dev_store_url = "xinqidianzi.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_orders,read_products,write_content,write_files,write_orders,write_products"

[auth]
redirect_urls = [
  "https://c752-60-176-176-114.ngrok-free.app/auth/callback",
  "https://c752-60-176-176-114.ngrok-free.app/auth/shopify/callback",
  "https://c752-60-176-176-114.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
